# Generated by Django 4.1.3 on 2022-11-16 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('valid', models.DateTimeField()),
                ('expired', models.DateTimeField()),
                ('discount', models.CharField(choices=[('10', '10%'), ('15', '15%'), ('25', '25%'), ('30', '30%'), ('50', '50%')], max_length=3)),
                ('available', models.BooleanField()),
            ],
        ),
    ]
